name: Compile Raspberry Pi Pico Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi

    - name: Set up Pico SDK
      run: |
        git clone -b master https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$PWD" >> $GITHUB_ENV

    - name: Build project
      env:
        PICO_SDK_PATH: ${{ env.PICO_SDK_PATH }}
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pico-gb-webcam-firmware
        path: build/pico_gb_printer_cam.uf2
